// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vatsal278/htmltopdfsvc/internal/logic (interfaces: HtmltopdfsvcLogicIer)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	model "github.com/PereRohit/util/model"
	gomock "github.com/golang/mock/gomock"
	model0 "github.com/vatsal278/htmltopdfsvc/internal/model"
)

// MockHtmltopdfsvcLogicIer is a mock of HtmltopdfsvcLogicIer interface.
type MockHtmltopdfsvcLogicIer struct {
	ctrl     *gomock.Controller
	recorder *MockHtmltopdfsvcLogicIerMockRecorder
}

// MockHtmltopdfsvcLogicIerMockRecorder is the mock recorder for MockHtmltopdfsvcLogicIer.
type MockHtmltopdfsvcLogicIerMockRecorder struct {
	mock *MockHtmltopdfsvcLogicIer
}

// NewMockHtmltopdfsvcLogicIer creates a new mock instance.
func NewMockHtmltopdfsvcLogicIer(ctrl *gomock.Controller) *MockHtmltopdfsvcLogicIer {
	mock := &MockHtmltopdfsvcLogicIer{ctrl: ctrl}
	mock.recorder = &MockHtmltopdfsvcLogicIerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHtmltopdfsvcLogicIer) EXPECT() *MockHtmltopdfsvcLogicIerMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockHtmltopdfsvcLogicIer) Ping(arg0 *model0.PingRequest) *model.Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(*model.Response)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockHtmltopdfsvcLogicIerMockRecorder) Ping(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockHtmltopdfsvcLogicIer)(nil).Ping), arg0)
}
